
package ru.taravkov.ifmo.webservices.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CarWebService", targetNamespace = "http://service.webservices.ifmo.taravkov.ru/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CarWebService {


    /**
     * 
     * @param color
     * @param rightHand
     * @param model
     * @param id
     * @param make
     * @param clazz
     * @return
     *     returns ru.taravkov.ifmo.webservices.client.OpStatus
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateCar", targetNamespace = "http://service.webservices.ifmo.taravkov.ru/", className = "ru.taravkov.ifmo.webservices.client.UpdateCar")
    @ResponseWrapper(localName = "updateCarResponse", targetNamespace = "http://service.webservices.ifmo.taravkov.ru/", className = "ru.taravkov.ifmo.webservices.client.UpdateCarResponse")
    @Action(input = "http://service.webservices.ifmo.taravkov.ru/CarWebService/updateCarRequest", output = "http://service.webservices.ifmo.taravkov.ru/CarWebService/updateCarResponse")
    public OpStatus updateCar(
        @WebParam(name = "id", targetNamespace = "")
        Long id,
        @WebParam(name = "make", targetNamespace = "")
        String make,
        @WebParam(name = "model", targetNamespace = "")
        String model,
        @WebParam(name = "color", targetNamespace = "")
        Color color,
        @WebParam(name = "clazz", targetNamespace = "")
        Clazz clazz,
        @WebParam(name = "rightHand", targetNamespace = "")
        Boolean rightHand);

    /**
     * 
     * @param color
     * @param rightHand
     * @param model
     * @param make
     * @param clazz
     * @return
     *     returns java.util.List<ru.taravkov.ifmo.webservices.client.Car>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findCar", targetNamespace = "http://service.webservices.ifmo.taravkov.ru/", className = "ru.taravkov.ifmo.webservices.client.FindCar")
    @ResponseWrapper(localName = "findCarResponse", targetNamespace = "http://service.webservices.ifmo.taravkov.ru/", className = "ru.taravkov.ifmo.webservices.client.FindCarResponse")
    @Action(input = "http://service.webservices.ifmo.taravkov.ru/CarWebService/findCarRequest", output = "http://service.webservices.ifmo.taravkov.ru/CarWebService/findCarResponse")
    public List<Car> findCar(
        @WebParam(name = "make", targetNamespace = "")
        String make,
        @WebParam(name = "model", targetNamespace = "")
        String model,
        @WebParam(name = "color", targetNamespace = "")
        Color color,
        @WebParam(name = "clazz", targetNamespace = "")
        Clazz clazz,
        @WebParam(name = "rightHand", targetNamespace = "")
        Boolean rightHand);

    /**
     * 
     * @param id
     * @return
     *     returns ru.taravkov.ifmo.webservices.client.OpStatus
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteCar", targetNamespace = "http://service.webservices.ifmo.taravkov.ru/", className = "ru.taravkov.ifmo.webservices.client.DeleteCar")
    @ResponseWrapper(localName = "deleteCarResponse", targetNamespace = "http://service.webservices.ifmo.taravkov.ru/", className = "ru.taravkov.ifmo.webservices.client.DeleteCarResponse")
    @Action(input = "http://service.webservices.ifmo.taravkov.ru/CarWebService/deleteCarRequest", output = "http://service.webservices.ifmo.taravkov.ru/CarWebService/deleteCarResponse")
    public OpStatus deleteCar(
        @WebParam(name = "id", targetNamespace = "")
        Long id);

    /**
     * 
     * @param color
     * @param rightHand
     * @param model
     * @param make
     * @param clazz
     * @return
     *     returns long
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createCar", targetNamespace = "http://service.webservices.ifmo.taravkov.ru/", className = "ru.taravkov.ifmo.webservices.client.CreateCar")
    @ResponseWrapper(localName = "createCarResponse", targetNamespace = "http://service.webservices.ifmo.taravkov.ru/", className = "ru.taravkov.ifmo.webservices.client.CreateCarResponse")
    @Action(input = "http://service.webservices.ifmo.taravkov.ru/CarWebService/createCarRequest", output = "http://service.webservices.ifmo.taravkov.ru/CarWebService/createCarResponse")
    public long createCar(
        @WebParam(name = "make", targetNamespace = "")
        String make,
        @WebParam(name = "model", targetNamespace = "")
        String model,
        @WebParam(name = "color", targetNamespace = "")
        Color color,
        @WebParam(name = "clazz", targetNamespace = "")
        Clazz clazz,
        @WebParam(name = "rightHand", targetNamespace = "")
        Boolean rightHand);

}
